### ISSUE TITLE
handletype

### ISSUE THREAD

**Issue by i-am-chris** [ThunderStruct/MSCircularSlider#1]
Hello, 

1. I want the handle to be an image. What do i need to do ?
2. Is it possible to animate the slider at the beginning to state the intent to slide? 

Thank you

**Comment by ThunderStruct** [comment]
Hi Chris!

I'm currently working on an update (releasing it really soon hopefully 🙏🏻) that will include both of these features

**Comment by i-am-chris** [comment]
cool


‌

**Comment by ThunderStruct** [comment]
The new version is released!
The animation part is still underway (and appended to the todo list), but I added a makeshift animation method using `Timer` in the example project for now, which you can find in the `SliderProperties` view controller.
Let me know if you have any other useful features in mind so I can include them in the next update! 😄

**Comment by i-am-chris** [comment]
Hello,
I am using Swift 3.2
I was trying to upgrade to the new version, i have all kind of pb. related to: 

MSCircularSliderHandle.swift:97:19: Method 'setAngle' with Objective-C selector 'setAngle:' conflicts with setter for 'angle' with the same Objective-C selector

let attributes = [NSAttributedStringKey.font: labelFont, NSAttributedStringKey.foregroundColor: labelColor] as [NSAttributedStringKey : Any]

**Comment by i-am-chris** [comment]
ok fixed: 
for swift3.2 : 
 let attributes = [NSFontAttributeName as NSString: labelFont, NSForegroundColorAttributeName as NSString:labelColor] as [NSString : Any]

**Comment by ThunderStruct** [comment]
Glad you got it fixed!
The `setAngle` conflict is resolved in 1.2.1
