### ISSUE TITLE
handle image rotation bug

### ISSUE THREAD

**Issue by Noiibe** [ThunderStruct/MSCircularSlider#10]
In MSCircularSliderHandle.swift

REPLACE

// Now, draw the rotated/scaled image into the context
        bitmap?.draw(img.cgImage!, in: CGRect(x: -img.size.width / 2, y: -img.size.height / 2, width: img.size.width, height: img.size.height))

BY

// Now, draw the rotated/scaled image into the context
        bitmap?.draw(img.cgImage!, in: CGRect(x: -rotatedSize.width / 2, y: -rotatedSize.height / 2, width: rotatedSize.width, height: rotatedSize.height))

**Comment by ThunderStruct** [comment]
Fixed in [1.3.0](https://github.com/ThunderStruct/MSCircularSlider/blob/master/CHANGELOG.md#130---02-07-2019). Thanks for pointing out the bug and solving it too!
