### ISSUE TITLE
Add a padding property to prevent labels to be clipped

### ISSUE THREAD

**Issue by Noiibe** [ThunderStruct/MSCircularSlider#11]
Add padding property to prevent labels to be clipped when  maximumAngle is like 260 and labelOffset is like 42 because the rotation of the frame clip the bottom left label.

Example in MSCircularSlider.swift:

let minimumSize = min(bounds.size.height - padding, bounds.size.width - padding)

**Comment by ThunderStruct** [comment]
Added in [1.3.0](https://github.com/ThunderStruct/MSCircularSlider/blob/master/CHANGELOG.md#130---02-07-2019). Thanks for your input!
