### ISSUE TITLE
can i get the real time angle of the handle?

### ISSUE THREAD

**Issue by sarahkee8** [ThunderStruct/MSCircularSlider#12]
Hi ThunderStruct, thanks for the great component.
Wondering if this component could get the real time angle or position (x,y)?
I tried to use slider.handle.angle / slider.handle.position - but both return 0.0 eventhough my handle was pointed in mid of the slider.
Thanks,
SK

**Comment by ThunderStruct** [comment]
Hi SK!
Appreciate your feedback!
If I understand you correctly, you want to read the handle's angle as you move it. You can do so by conforming to the `MSCircularSliderDelegate` protocol and using the method `circularSlider(MSCircularSlider, valueChangedTo, fromUser)`, which gets called continuously as the value changes.

Refer to the example project (`SliderPropertiesVC.swift` lines 107-109 specifically). Don't forget to set `slider.delegate = self`!

**Comment by sarahkee8** [comment]
Hi ThunderStruct,
Thanks so much for your prompt reply. It works now and really appreciated your help.
Thanks,
SK

**Comment by ThunderStruct** [comment]
Hi SK!
You're very welcome. Glad I could help out. :-)
Good luck!
