### ISSUE TITLE
possible regression? programatically setting slider currentValue doesn't update UI

### ISSUE THREAD

**Issue by ghost** [ThunderStruct/MSCircularSlider#14]
This was working fine in 1.2.2, and has possibly regressed?

I set self.slider.currentValue = default to reset it via a button. This used to update the slider position before, now there's no change.

(unless there's a new recommended way of doing this now?)

**Comment by ThunderStruct** [comment]
Hi!

I just tested it and setting `slider.currentValue` to any value updates the handle's position appropriately. Could you please share some of the code with me so I can pinpoint the issue? Please include the slider's instantiation settings (the values of `maximumAngle`, etc...)!

**Comment by ghost** [comment]
A full recompilation fixed this -- very odd indeed.
