### ISSUE TITLE
tap in iPhone 6 not work 

### ISSUE THREAD

**Issue by RoeeNadam** [ThunderStruct/MSCircularSlider#15]
first I want to recommend this a grate slider works grate but I need to add a tap in slider to jump to value in iPhone 6.

**Comment by ThunderStruct** [comment]
Hi!

I'm glad you found it helpful!
As of now, you can only tap and slide anywhere on the slider to change the value. I'll add an option to change the value by just tapping in the next version!

**Comment by RoeeNadam** [comment]
thanks for the quickly replay (-:
I don't understand what you mean "you can only tap and slide anywhere on the slider to change the value"
my problem is that tap works in iPhone 7,8,x,xs but in 6 and 6S the tap not works.

**Comment by ThunderStruct** [comment]
No problem! :-)
I meant that if you **drag** anywhere on the slider, the handle will snap to the point you dragged across. But if you only **tap**, it won't move.
Could you please explain a bit more how the tap works on some devices and not others? If you can share some of your code (or a brief project that shows the issue), I'll be able to pinpoint the problem much faster!

**Comment by RoeeNadam** [comment]
just run in iPhone 6 or 6s you see that tap not work, when I check in
iPhone XS and iPhone 7 tap works.

**Comment by ThunderStruct** [comment]
I'm getting the same exact behavior on both devices (iPhone 6 and iPhone 7)!
