### ISSUE TITLE
Handle image isn't rotating.

### ISSUE THREAD

**Issue by jainam** [ThunderStruct/MSCircularSlider#2]
I set an image to the handleImage property of the slider. But the image is appearing straight even when I move the handle. 
I want the image to also rotate with the angle of the handle.

Current output is as so: 
![screen shot 2018-06-19 at 4 49 08 pm](https://user-images.githubusercontent.com/12856809/41594536-5662879e-73e1-11e8-95c7-8f93608e84e2.png)

![screen shot 2018-06-19 at 4 49 24 pm](https://user-images.githubusercontent.com/12856809/41594545-5cc9e05a-73e1-11e8-83e9-8ba472899f43.png)

Is there any way I can achieve the rotation ?

Thanks in advance!

**Comment by ThunderStruct** [comment]
Hi!

I just pushed a new version to CocoaPods that includes a new `handleRotatable` member. If you set it to `true`, it will rotate the handle image as you slide it. You can also set it from the storyboard attributes inspector.

Good luck!

**Comment by ThunderStruct** [comment]
Hi!

I just pushed a new version to CocoaPods that includes a `handleRotatable` member. If you set it to `true`, it will rotate the handle image as you slide it. You can also set it from the storyboard attributes inspector.

Good luck!

**Comment by jainam** [comment]
@ThunderStruct , 

Thanks a ton for your instant reply and solution. 

The image has started rotating but that has somehow blurred the image completely and while the handle is being moved, the image's height grows smaller and bigger.
I'm attaching a few screenshots and a dropbox link for a video which show this behaviour. Could you please look into that and see why that is happening or what I need to change for that?

![screen shot 2018-06-20 at 2 57 54 pm](https://user-images.githubusercontent.com/12856809/41649942-7812f95a-749a-11e8-8ce1-732b533f2dfc.png)
![screen shot 2018-06-20 at 2 58 12 pm](https://user-images.githubusercontent.com/12856809/41649947-7a5afabe-749a-11e8-973d-f4a6de07da7f.png)
![screen shot 2018-06-20 at 2 58 27 pm](https://user-images.githubusercontent.com/12856809/41649952-7cf8556e-749a-11e8-817c-6ce6e541e9af.png)
![screen shot 2018-06-20 at 2 58 42 pm](https://user-images.githubusercontent.com/12856809/41649956-7efa8940-749a-11e8-91cf-59ae19212e94.png)

Video: https://www.dropbox.com/s/9vtyz4n3vjzdeay/CircularSliderDemo.mov?dl=0

Thanks again!

**Comment by jainam** [comment]
Also, you see, in the above demo example, as the value increases, the whole bar color changes. Instead the actual color should persist and only the color at the handle position should appear. 

Kind of like so...

![screen shot 2018-06-20 at 4 20 08 pm](https://user-images.githubusercontent.com/12856809/41654321-b64b2fba-74a6-11e8-86d2-3aa66378f7e9.png)

See how here the initial blue remains the same and a lighter blue shaded is aded to the bar as the handle is moved?
