### ISSUE TITLE
Max Rotation Bound

### ISSUE THREAD

**Issue by anthonyessaye** [ThunderStruct/MSCircularSlider#4]
I don't know if this is actually possible. I need a 360 degree circle to stop at the max and the user can only rewind back to 0 after that, instead of it looping endlessly

**Comment by ThunderStruct** [comment]
Apologies for being late! Added in [1.3.0](https://github.com/ThunderStruct/MSCircularSlider/blob/master/CHANGELOG.md#130---02-07-2019).
