### ISSUE TITLE
Latest version 1.2.2 is not up to date with master

### ISSUE THREAD

**Issue by Noiibe** [ThunderStruct/MSCircularSlider#9]
This works:

pod 'MSCircularSlider', :git => 'https://github.com/ThunderStruct/MSCircularSlider.git', :branch => 'master'

but this is not the latest version of master:

pod 'MSCircularSlider', '1.2.2'

**Comment by ThunderStruct** [comment]
Apologies for being late. Released [1.3.0](https://github.com/ThunderStruct/MSCircularSlider/releases/tag/1.3.0) and updated the pod!

**Comment by Noiibe** [comment]
Hi,

I try to install the pod version 1.3.0 with "platform :ios, '11.0'" in my Podfile and I get this error:

[!] CocoaPods could not find compatible versions for pod "MSCircularSlider":
  In Podfile:
    MSCircularSlider (= 1.3.0)

Specs satisfying the `MSCircularSlider (= 1.3.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by ThunderStruct** [comment]
Hi,
Thanks for that! I accidentally bumped up the minimum deployment target to 12.2. It should be fixed now!
